version: '3'

services:
  flask:
    build: ./server
    container_name: server
    restart: always
    environment:
      - APP_NAME=MyFlaskApp
    expose: 8080

  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"

  vue:
    build: ./client
    container_name: vuejs
    restart: always
